### ISSUE TITLE
RunAsTI64.exe is seen as a 32-bit exe

### ISSUE THREAD

**Issue by FabrizioMarana** [jschicht/RunAsTI#2]
When executing under normal CMD, elevated CMD and even system CMD (tried all 3) RunAsTI64 gives the following message:

C:\Users>RunAsTI64 /?
This version of c:\bin\RunAsTI64.exe is not compatible with the version of Windo
ws you're running. Check your computer's system information to see whether you n
eed a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the
software publisher.

More info:
C:\Users>ver

Microsoft Windows [Version 6.1.7601]

Tried downloading it again, have not tried running interpreted code...

**Comment by kevinvanrijn** [comment]
If you can't run `RunAsTI64.exe` use `RunAsTI.exe` instead. It'll be functionally equivalent.

Also, is your Windows 64-bit?

**Comment by FabrizioMarana** [comment]
Yes, 64-bit version of Windows 7. :(

**Comment by FabrizioMarana** [comment]
![capture](https://cloud.githubusercontent.com/assets/8290759/17053611/1ef4acdc-5003-11e6-8316-f85fa1cd1e49.PNG)

**Comment by kevinvanrijn** [comment]
I did a quick search on Google and this appears to be an issue with badly configured Windows settings in the registry. I suggest doing some research into this yourself and doing a clean reinstall of Windows if at all possible.

Two other things this could be is an issue with your antivirus, that shouldn't be producing this type of error message, and a corrupt download, which seems unlikely since you downloaded it multiple times.

**Comment by FabrizioMarana** [comment]
Oops, apologies for not closing this issue earlier: it was my corporate build...
